# Generated by Django 4.2.1 on 2023-05-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
